function varargout = Help_AirConditioner(varargin)
% HELP_AIRCONDITIONER MATLAB code for Help_AirConditioner.fig
%      HELP_AIRCONDITIONER, by itself, creates a new HELP_AIRCONDITIONER or raises the existing
%      singleton*.
%
%      H = HELP_AIRCONDITIONER returns the handle to a new HELP_AIRCONDITIONER or the handle to
%      the existing singleton*.
%
%      HELP_AIRCONDITIONER('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in HELP_AIRCONDITIONER.M with the given input arguments.
%
%      HELP_AIRCONDITIONER('Property','Value',...) creates a new HELP_AIRCONDITIONER or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before Help_AirConditioner_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to Help_AirConditioner_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help Help_AirConditioner

% Last Modified by GUIDE v2.5 23-Mar-2012 22:49:01

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @Help_AirConditioner_OpeningFcn, ...
                   'gui_OutputFcn',  @Help_AirConditioner_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before Help_AirConditioner is made visible.
function Help_AirConditioner_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to Help_AirConditioner (see VARARGIN)

axes(handles.axes1)
[x,map]=imread('AC_model.jpg','jpg');
image(x),colormap(map),axis off,hold on

axes(handles.axes2)
[x,map]=imread('AA.jpg','jpg');
image(x),colormap(map),axis off,hold on



% Choose default command line output for Help_AirConditioner
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);

% UIWAIT makes Help_AirConditioner wait for user response (see UIRESUME)
% uiwait(handles.figure1);


% --- Outputs from this function are returned to the command line.
function varargout = Help_AirConditioner_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;


text1  = {'Air Conditioner (AC)'};
% Create a text
set(handles.text1,'Units', 'characters',...
                 'Position', [1 26.5 30 1.5],...
                 'String',  text1,...
                 'FontSize',  12);

text2  = {'AC equipment is often described by its cooling capacity in terms of BTU, which is the amount of energy used by the',...
    'equipment to remove heat from the air, regulating the temperature and humidity, therefore circulation of air in a room or',... 
    'the entire house.'...
    ''...
    'Basically there are two types of AC: window and central type. The common room AC (window AC) capacity is around 6000-18000BTU. Central AC with a split configuration use ducts or pipes to distribute cool air to one or more rooms and their capacity is around 9000-60000BTU.'...
    };
% Create a text
set(handles.text2,'Units', 'characters',...
                 'Position', [2 16.5 141 10],...
                 'String',  text2,...
                 'FontSize',  10);

text3  = {'The modeling of the AC is depicted in the figure bellow and its corresponds equation is [1]. This represents the measurement of how much cooling effect is provided by the AC and it is known as the Energy Efficiency Ratio (EER). In this equation, Qout is the energy required to extract the heat (Qin) in the cooling space. An electrical input Win (in Watts) is required to do this work.'};
% Create a text
set(handles.text3,'Units', 'characters',...
                 'Position', [2 12 141 5],...
                 'String',  text3,...
                 'FontSize',  10);
             
text4  = {'      Capacity (BTU):',...
    '',...
    'Voltage (Volts):',...
    '',...
    'Current (Ampers):',...
    '',...
    'Power (Watts):',...
    '',...
    '(EER) Energy efficiency ratio:',...
};
% Create a text
set(handles.text4,'Units', 'characters',...
                 'HorizontalAlignment','right',...
                 'Position', [31 1 30 10],...
                 'String',  text4,...
                 'FontSize',  8);


text5  = {'----->',...
    '',...
    '----->',...
    '',...
    '----->',...
    '',...
    '----->',...
    '',...
    '----->',...
};
% Create a text
set(handles.text5,'Units', 'characters',...
                 'Position', [69 4.5 7 13],...
                 'String',  text5,...
                 'FontSize',  8);

text6  = {'Chose the capacity of your AC (BTU).',...
    '',...
    'Set voltage usually 230V or 120V (Volts).',...
    '',...
    'Place the consumed current (Ampers).',...
    '',...
    'Power consumption (Watts).',...
    '',...
    'Set the Energy Efficiency Factor (EER).',...
};             
% Create a text
set(handles.text6,'Units', 'characters',...
                 'HorizontalAlignment','left',...
                 'Position', [2 1 60 10],...
                 'String',  text6,...
                 'FontSize',  8);

text7  = {'Refer to [2] to find the types of AC in households.'}; 
set(handles.text7,'Units', 'characters',...
                 'HorizontalAlignment','left',...
                 'Position', [75 4 60 2],...
                 'String',  text7,...
                 'FontSize',  8);

text8  = {'References',...
    '[1] A. Molina, A Gabeldon, J.A. Fuentes and C. Alvarez, "Implementation and assessment of physically based electricl load models: application to direct',...
    '    load control residential programmes", IEE Proc-Gener. Tranm. Sistrib., vol. 150, no. 1, January 2003.',...
    '[2] http://www.furnacecompare.com/air-conditioners/'};

% Create a uitable on the left side of the figure
set(handles.text8,'Units', 'characters',...
                 'Position', [5 0 145 5],...
                 'String',  text8,...
                 'FontSize',  8);
             
             
% --- Executes on selection change in listbox2.
function listbox2_Callback(hObject, eventdata, handles)
% hObject    handle to listbox2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = cellstr(get(hObject,'String')) returns listbox2 contents as cell array
%        contents{get(hObject,'Value')} returns selected item from listbox2


% --- Executes during object creation, after setting all properties.
function listbox2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to listbox2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: listbox controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
